Wb/signer addr
provenance-io/aggregate-service pull request #39
Opened 2022-04-19 19:26 UTC by wbaker-figure

2022-04-19 21:07 UTC, rchaing-figure requested changes

2022-04-19 21:07 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +        Keys.PubKey.parseFrom(it.publicKey.value).key.toByteArray().sha256hash160().toBech32(hrp).address.value
:/ 

nice work, this looked like a pain

2022-04-19 21:07 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +                null
is this null needed?

2022-04-19 21:07 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +    fee: Pair<Long?, String?>?
Optional, might be cleaner, we could create a simple one line data class for Fee(fee, denom)

2022-04-19 21:07 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/TxError.kt
> +    val denom: String
nit-picky, could fee and denom be together? (Fee data class would probably relieve this pain)

2022-04-19 21:15 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/Config.kt
> +    val hrp: String,
This is the prefix for the signer addr whether it be testnet or prod, hrp is the "tp"/"pb" I believe that prefixes the addresses

2022-04-20 01:25 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +fun io.provenance.eventstream.stream.models.BlockResultsResponseResult.blockEvents(blockDateTime: OffsetDateTime?): List<BlockEvent> = run {
Nah, Seems in this use case it is basically just a different way to encapsulate the code. I made the syntax match the across the other functions as well 👍.  After looking it up more, it just scopes the variable it is used on to "this" which wasn't being used anyway.

2022-04-20 01:33 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +        Keys.PubKey.parseFrom(it.publicKey.value).key.toByteArray().sha256hash160().toBech32(hrp).address.value
🎢

2022-04-20 01:34 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +        signerAddr = signerAddr,
❤️

2022-04-20 01:36 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +    fee: Pair<Long?, String?>?
I can get behind this. First and second is super explanatory and all but...

2022-04-20 01:43 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +                null
I removed it and I am not seeing anything wrong with mismatched anything. My only fear was that the mapIndexed txsResults may give misaligned indexes. But I ran it for awhile and all the signer addresses/fees were matching expected values. Looks good.

2022-04-20 14:06 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/TxError.kt
> +data class Fee(
We could probably move this to another file, i think we can add the signer addr in this data class as well as the wallet addr that incurred the fee? thoughts?

2022-04-20 14:07 UTC, rchaing-figure approved these changes
Nice work!, just one more thought on the Fee data class.

2022-04-20 21:31 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +        var feeIncurringAddr = ""
think you can assign this to the if statement and change it to a `val`; and I think IntelliJ complained about using a `when` statement instead of the cascading `if`?

2022-04-20 21:31 UTC, rchaing-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +            Fee(amount, denom, signerAddr, feeIncurringAddr)
is the signerAddr and feeIncurringAddr always diff/same?

2022-04-20 22:00 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +            Fee(amount, denom, signerAddr, feeIncurringAddr)
It can be different or the same. See [here](https://explorer.test.provenance.io/tx/6662F25C449BC6EDC9AAF96C898ED4A9818D21128B649960D565AC68684DEEAC)
Granter is different from the signer and it is the one that picks up the fee

2022-04-20 22:04 UTC, wbaker-figure commented on common/src/main/kotlin/io/provenance/aggregate/common/models/Extensions.kt
> +        var feeIncurringAddr = ""
✅

2022-04-20 22:30 UTC, merged